### ISSUE TITLE
Firefox: SVG text isn't selectable

### ISSUE THREAD

**Issue by ceane** [TimPietrusky/background-clip-text-polyfill#2]
I don't think you can do much about this, but SVG text is unselectable in Firefox. 0.o

Here's a bug report of it:
https://bugzilla.mozilla.org/show_bug.cgi?id=330046

You may want to submit a comment letting them know.

I suggest also adding the title attribute to the SVG element with the text inside, that way at least screen readers can read the text.

**Comment by christianbundy** [comment]
This issue has been solved, as found in the above link and testable here: http://svg-whiz.com/svg/w3c/textSelection.svg
